// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0HUda8GzJvqjYx1BwN4GKCbMAZ6Ki8O4',
    appId: '1:693297060290:web:bab15aac8c6fa98cbc1e5b',
    messagingSenderId: '693297060290',
    projectId: 'virtual-try-on-496e5',
    authDomain: 'virtual-try-on-496e5.firebaseapp.com',
    storageBucket: 'virtual-try-on-496e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqRPNxOx8F7SDEauljfvEQpVU5I9BJPvk',
    appId: '1:693297060290:android:dcf95a8251afa61fbc1e5b',
    messagingSenderId: '693297060290',
    projectId: 'virtual-try-on-496e5',
    storageBucket: 'virtual-try-on-496e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzJkNi64ULMgGOtNU0lxSAzasATZH-UFc',
    appId: '1:693297060290:ios:2959926b6834392fbc1e5b',
    messagingSenderId: '693297060290',
    projectId: 'virtual-try-on-496e5',
    storageBucket: 'virtual-try-on-496e5.firebasestorage.app',
    iosBundleId: 'com.example.virtualtryon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzJkNi64ULMgGOtNU0lxSAzasATZH-UFc',
    appId: '1:693297060290:ios:2959926b6834392fbc1e5b',
    messagingSenderId: '693297060290',
    projectId: 'virtual-try-on-496e5',
    storageBucket: 'virtual-try-on-496e5.firebasestorage.app',
    iosBundleId: 'com.example.virtualtryon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0HUda8GzJvqjYx1BwN4GKCbMAZ6Ki8O4',
    appId: '1:693297060290:web:cb71cefb8de24f36bc1e5b',
    messagingSenderId: '693297060290',
    projectId: 'virtual-try-on-496e5',
    authDomain: 'virtual-try-on-496e5.firebaseapp.com',
    storageBucket: 'virtual-try-on-496e5.firebasestorage.app',
  );
}
